### PR TITLE
make boilerplate-update

### PR DESCRIPTION
**Pull request by mjlshen**
Keeping this repo up-to-date with boilerplate

`make boilerplate-update`
`make ensure-fips`
`make generate`

### CODE REVIEW

**Review by 2uasimojo — COMMENTED** [review]
Looks sane. Just one thing: Did go.sum not get updated? If `go mod tidy` yields a diff, we should consider adding that to `validate`. (Ditto `go mod vendor` for projects with vendored deps.)

**Comment by mjlshen** [comment]
It didn't, this repo's `go.mod` was slightly misformatted and had 3 "require" blocks

```
require direct deps

require some indirect deps

require the rest of the indirect deps
```

I just combined the bottom two indirect dependency blocks into one and let `go fmt .` sort them as it wanted to

**Comment by 2uasimojo** [comment]
Ah, okay, I see that now. I didn't look that closely before :)

/lgtm for boilerplate

**Comment by mjlshen** [comment]
I just want to try this since it already has the necessary approvals in spirit
/lgtm

**Comment by 2uasimojo** [comment]
okay then

/lgtm

**Pull request merged**
