### PR TITLE
Enable FIPS build

### PR DESCRIPTION
**Pull request by wanghaoran1988**
[SDE-1954](https://issues.redhat.com//browse/SDE-1954) This is for FedRAMP change control purposes

### CODE REVIEW

**Comment by wshearn** [comment]
Should also add this for FIPS inside splunk
https://docs.splunk.com/Documentation/Splunk/8.2.6/Security/SecuringSplunkEnterprisewithFIPS (this also applies to the forwarders and the heavy forwarders)

**Comment by wanghaoran1988** [comment]
@wshearn We are not using splunk enterprise right? do you mean we need rebuilt our forwarder image to start with fips enabled here https://github.com/openshift/splunk-forwarder-images/blob/master/containers/heavy_forwarder/bin/run.sh ?

**Pull request merged**
