### PR TITLE
boilerplate update + migration to crdv1

### PR DESCRIPTION
**Pull request by bng0y**

### CODE REVIEW

**Comment by fahlmant** [comment]
https://issues.redhat.com/browse/OSD-7603

**Comment by 2uasimojo** [comment]
bp update is good.

CRD installs cleanly.

`oc explain` works.

(Aside: `oc explain` doesn't provide any useful information. Adding description comments to the fields in [splunkforwarder_types.go](https://github.com/openshift/splunk-forwarder-operator/blob/2509df04d39ea6d81cd1b1c2e20b8d479e6c6e11/pkg/apis/splunkforwarder/v1alpha1/splunkforwarder_types.go) would resolve this.)

**Comment by 2uasimojo** [comment]
> (Aside: `oc explain` doesn't provide any useful information. Adding description comments to the fields in [splunkforwarder_types.go](https://github.com/openshift/splunk-forwarder-operator/blob/2509df04d39ea6d81cd1b1c2e20b8d479e6c6e11/pkg/apis/splunkforwarder/v1alpha1/splunkforwarder_types.go) would resolve this.)

Opened OSD-7764 for this.

**Comment by 2uasimojo** [comment]
Hello

/lgtm

**Pull request merged**
