### PR TITLE
OSD-21522 - New image update for forwarder

### PR DESCRIPTION
**Pull request by theautoroboto**
Updating the image to one with no CVE's.

### CODE REVIEW

**Comment by tonytheleg** [comment]
I think you might be missing a make command step here (`make image-digests`). You update sets a parameter for the latest splunk forwarder image tag, but the olm-template needs to be updated for the new image hashes for actually deply the new splunk forwarders

See [HERE](https://github.com/openshift/splunk-forwarder-operator/blob/a3cc234d404e3fd032eb4b045c65dc8e2c733bb5/hack/olm-registry/olm-artifacts-template.yaml#L334)

im thinking that make command will update those values for you based on this parameter you just set

**Review by fahlmant — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
