### PR TITLE
[OSD-18401] On MCs index the eve-*.json files from suricata.

### PR DESCRIPTION
**Pull request by bergmannf**
Adds the eve logs from suricata to a new index in Splunk for hypershift management-clusters.

### CODE REVIEW

**Comment by bergmannf** [comment]
PR is on hold as this is mostly to get all required changes opened, but right now the index does not exist yet.

**Comment by dustman9000** [comment]
Feel free to unhold once the indices are created, thanks!
/lgtm
/approve

**Review by sam-nguyen7 — CHANGES_REQUESTED** [review]

**Pull request merged**
